# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CDT - Home
description: Cloudeteer Home with all kind of usefull information regarding projects and organization stuff
# baseurl: /cdt # the subpath of your site, e.g. /support
url: https://github.cloudeteer.de/ # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type:  #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
brand_logo_long: logo_long.png
brand_name: Cloudeteer
header: How can we help you?
subheader: Support and documentation for Cloudeteer

meta_image: odin-meta.png

# Social Links
twitter_username: cloudeteer
facebook_page:
github_username: cloudeteer
email: support@cloudeteer.de
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/cloudeteer

nav_item_two: LinkedIn
nav_item_two_link: https://de.linkedin.com/company/cloudeteer-gmbh

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Cloudeteer Home
nav_button_link: https://github.cloudeteer.de/

# More Help
help_one_title: Provide Feedback
help_one_content: You can give feedback and also participate in discussion on how we can improve this page
help_one_button: Github Discussion
help_one_link: https://github.com/cloudeteer/cdt-2.0/discussions

help_two_title: Site Content
help_two_content: If you feel like something is missing or needs to be updated on this page just have a look here
help_two_button: Page Wiki
help_two_link: https://github.com/cloudeteer/cdt-home/wiki

help_three_title: Cloudeteer Community
help_three_content: We also have a Community Repository in which you can find non-work related stuff like sell offers.
help_three_button: Github Repo
help_three_link: https://github.com/cloudeteer/community/discussions

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
