# This is a basic workflow to help you get started with Actions

name: Create_Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: assets/
          dest: zipperino.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "zipperino.zip"
          bodyFile: "README.md"
          token: ${{ secrets.MY_SECRET }}
